// DO NOT EDIT — generated by scripts/deploy.sh. Re-run to point the agent
// dashboard at a freshly deployed set of testnet contracts (shared with the
// sender app so both frontends see the same on-chain state).
export const CONTRACTS = {
  testnet: {
    network: "testnet",
    networkPassphrase: "Test SDF Network ; September 2015",
    rpcUrl: "https://soroban-testnet.stellar.org",
    escrow: "CDZUUMGZN37CCZMNHOPLSUDNCFRBYX6MQGAD555V77JZGZ6PE237EMV5",
    registry: "CB57PKZYHJWULH7EQPZXLZQVTUCESXQRLMEKEC6K5YUESOMSRWSYC6LI",
    oracle: "CAHCKDO4GZ5PMVMAY2SAIMXWTXJS5VZZXL3M27GVSN7PRCALJMJ3TTXX",
    token: "CBYTWY3R5A4KFALS4O4IM4HXWW5VJDSBDACNH5NGR6DOJ3ILJEZNKWK2",
    tokenCode: "DEMOUSDC",
    tokenIssuer: "GCFGKLCBV5IGJYGRR7FJNU53HFV5674PMQNNJT6HRAFGUAHZ7V3ZELXR",
    tokenDecimals: 7,
    corridor: {
      id: "USNG",
      base: "USDC",
      quote: "NGN",
      protocolFeeBps: 100,
      agentFeeBps: 200,
    },
  },
}
